### ISSUE TITLE
Missing features in Watchdog

### ISSUE THREAD

**Issue by surirohit** [auvnitrkl/hammerhead#1]
@YikeStone Please solve these issues

Important issues:- 
- Topic of thruster speed is incorrect
- Please insert comments on what the timer is doing
- Watchdog label doesn't turn red when data is not received for 5 seconds
- Set proper file names (.cpp, .h and .ui)
- Change object name of ui to Watchdog rather than MainWindow 
- Set executable name to `watchdog`
- Move include files to `include/watchdog/`
- App does not exit when closed using close button. `while(ros::ok())` is not the best thing to do here. Check  `thruster_controller.cpp` code.

Optional for now but needed to be done later:-
- Improve formatting of UI
- Update README.md
- Remove unnecessary lines from CMakeLists.txt and package.xml

**Comment by YikeStone** [comment]
All Done accept formatting of UI
